---
# All servers common variables
ansible_user: ubuntu
ansible_ssh_pass: Proxmox10022000
ansible_become: yes
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3

# Timezone
timezone: Europe/Amsterdam

# SOC Network configuration
soc_network: 192.168.50.0/24
honeypot_network: 192.168.52.0/24
